### PR TITLE
Issue #109 custom font (using typeface) Fixed 

### LINKED ISSUE #109: Custom Font
Hi
Thanks for your great lib.

Would you please add a function for changing typeface?
Of course I can use custom view, but if you add it it would save time :)

### PR DESCRIPTION
**Pull request by shynline**
#109

### CODE REVIEW

File: fancyshowcaseview/src/main/java/me/toptas/fancyshowcase/internal/Properties.kt [hunk 1]
```diff
@@ -45,7 +46,8 @@ internal data class Properties(
         var dismissListener: DismissListener? = null,
         var queueListener: OnQueueListener? = null,
         var focusedView: IFocusedView? = null,
-        var clickableView: IFocusedView? = null
+        var clickableView: IFocusedView? = null,
+        var typeface: Typeface? = null
```
Comment (faruktoptas) [inline fancyshowcaseview/src/main/java/me/toptas/fancyshowcase/internal/Properties.kt:50]: android specific properties are grouped and `AndroidProperties` class. Please move this param under this data class.

**Comment by faruktoptas** [comment]
Thank you for your contribution @shynline :)
